import type { NextPage } from "next";
import Head from "next/head";
import { Todo } from "../model/todo.model";
import Form from "../components/Form";
import TodoList from "../components/TodoList";

interface prop {
  data: Todo[];
}

const Home: NextPage<prop> = () => {
  return (
    <div className="flex flex-col justify-center items-center h-screen min-h-screen">
      <Head>
        <title>Todolist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`w-full flex flex-col flex-1 justify-between  mb-5 px-20`}
      >
        <h1 className="flex justify-center w-full text-2xl font-bold p-5">
          Todolist
        </h1>
        <TodoList />
        <Form />
      </main>

      <footer className="flex justify-center items-center w-full h-20 bg-gray-100">
        <small>&copy; 2021 YUDAI1995</small>
      </footer>
    </div>
  );
};

export default Home;
